In [ ]:
import tensorflow as tf
from tensorflow import keras

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
from google.colab import files
data=files.upload()
data=pd.read_csv("Data1 (1).csv")

Saving Data1 (1).csv to Data1 (1).csv


In [ ]:
x=data.iloc[::,:-1]
y=data.iloc[::,-1]
print(y.ndim)
y=np.array([y]).T
print(x)

1
    outlook   Temperature  Humidity  Wind
0          1            1         1     1
1          1            1         1     2
2          2            1         1     1
3          3            2         1     1
4          3            3         2     1
5          3            3         2     2
6          2            3         2     2
7          1            2         1     1
8          1            3         2     1
9          3            2         2     1
10         1            2         2     2
11         2            2         1     2
12         2            1         2     1
13         3            2         1     2


In [ ]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)

print(x_train,y_train)

    outlook   Temperature  Humidity  Wind
2          2            1         1     1
13         3            2         1     2
9          3            2         2     1
1          1            1         1     2
7          1            2         1     1
10         1            2         2     2
3          3            2         1     1
0          1            1         1     1
5          3            3         2     2
12         2            1         2     1 2     1
13    0
9     1
1     0
7     0
10    1
3     1
0     0
5     0
12    1
Name: Play Tennis, dtype: int64


In [ ]:
np.random.seed(1)

synaptic_weights=2*np.random.random((4,1))-1

print("synaptic weights")

print(synaptic_weights)

synaptic weights
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]
 [-0.39533485]]


In [ ]:

def sigmoid(x):
  return(1/(1+np.exp(-x)))


def derivative_sigmoid(x):
  return(x*(1-x))



In [ ]:
for iteration in range(100000):
  input_layer=x
  output=sigmoid(np.dot(input_layer,synaptic_weights))
  error=y-output
  adjustments=error*derivative_sigmoid(output)
  synaptic_weights+=np.dot(input_layer.T,adjustments)



In [ ]:
print("synatic weights after training are")

print(synaptic_weights)


synatic weights after training are
[[ 0.66801705]
 [-1.62845145]
 [ 5.40374943]
 [-3.75597263]]


In [ ]:
print("output")

output=np.rint(output)
print(output)

output
[[1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]]


In [ ]:
from sklearn.metrics import accuracy_score
scr=accuracy_score(y,output)
print(scr)

0.7857142857142857


In [ ]:

input_shape = [x.shape[1]]
model = tf.keras.Sequential([
 
    tf.keras.layers.Dense(units=64, activation='relu',
                          input_shape=input_shape),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=1)
])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 64)                320       
                                                                 
 dense_4 (Dense)             (None, 64)                4160      
                                                                 
 dense_5 (Dense)             (None, 1)                 65        
                                                                 
Total params: 4,545
Trainable params: 4,545
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# adam optimizer works pretty well for
# all kinds of problems and is a good starting point
model.compile(optimizer='adam', 
               
              # MAE error is good for
              # numerical predictions
              loss='mae') 

In [ ]:

losses = model.fit(x, y,
 
                   validation_data=(x, y),
                    c
                   # it will use 'batch_size' number
                   # of examples per example
                   batch_size=256,
                   epochs=200,  # total epoch
 
                   )

Epoch 1/200
1/1 [==============================] - 0s 50ms/step - loss: 0.0101 - val_loss: 0.0244
Epoch 2/200
1/1 [==============================] - 0s 35ms/step - loss: 0.0244 - val_loss: 0.0335
Epoch 3/200
1/1 [==============================] - 0s 36ms/step - loss: 0.0335 - val_loss: 0.0198
Epoch 4/200
1/1 [==============================] - 0s 54ms/step - loss: 0.0198 - val_loss: 0.0143
Epoch 5/200
1/1 [==============================] - 0s 37ms/step - loss: 0.0143 - val_loss: 0.0232
Epoch 6/200
1/1 [==============================] - 0s 34ms/step - loss: 0.0232 - val_loss: 0.0100
Epoch 7/200
1/1 [==============================] - 0s 36ms/step - loss: 0.0100 - val_loss: 0.0200
Epoch 8/200
1/1 [==============================] - 0s 38ms/step - loss: 0.0200 - val_loss: 0.0245
Epoch 9/200
1/1 [==============================] - 0s 36ms/step - loss: 0.0245 - val_loss: 0.0067
Epoch 10/200
1/1 [==============================] - 0s 46ms/step - loss: 0.0067 - val_loss: 0.0237
Epoch 11/200
1/1 [=

In [ ]:
model.predict(x.iloc[0:3, :])

1/1 [==============================] - 0s 20ms/step


array([[-0.00513042],
       [ 0.0087631 ],
       [ 0.9858109 ]], dtype=float32)

In [ ]:
y[0:3]

array([[0],
       [0],
       [1]])

In [ ]:
output=model.predict(x)
output=np.rint(output)


1/1 [==============================] - 0s 33ms/step


In [ ]:
print(np.rint((model.predict([[2,1,2,1]]))))

1/1 [==============================] - 0s 37ms/step
[[1.]]


In [ ]:
srcc=accuracy_score(y,output)
print(srcc)

1.0
